#Usage: python master_orchestrator.py --csv "Datasets/Housing.csv" --target "price" --dataset-context "Real estate price prediction dataset with house features" --save-memory
"""
Master Orchestrator Agent

This agent orchestrates the complete workflow across all agents:
1. Preprocessing Agent - Generate dataset report, preprocessing plan, and code
2. LLM Orchestrator (Reasoning Agent) - Model recommendations and validation code
3. Improvement Agent - Optimization and improvements

The master agent maintains ultimate memory of all agents and manages the workflow,
similar to how preprocessing_workflow_agent.py manages its workflow.
"""

import json
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Any, Literal, Optional, TypedDict

from langgraph.graph import END, StateGraph  # type: ignore[import]

from llm_config import DEFAULT_LLM_MODEL, DEFAULT_LLM_ENDPOINT

# Add paths for imports
# Master orchestrator is in the root IntelliModel folder
project_root = Path(__file__).parent
preprocessing_dir = project_root / "Pre Processing Agent"
# LLM Orchestrator lives in the 'LLM Orchestrator' folder (not 'Reasoning Agent')
reasoning_dir = project_root / "LLM Orchestrator"
improvement_dir = project_root / "Improvement Agent"

# Add to path for imports
if str(preprocessing_dir) not in sys.path:
    sys.path.insert(0, str(preprocessing_dir))
if str(reasoning_dir) not in sys.path:
    sys.path.insert(0, str(reasoning_dir))


@dataclass
class MasterMemory:
    """Ultimate memory structure that tracks everything across all agents."""
    # Core dataset information
    dataset_path: Optional[Path] = None
    target_column: Optional[str] = None
    dataset_name: Optional[str] = None
    context_of_dataset: Optional[str] = None
    task_type: Optional[str] = None
    
    # Preprocessing Agent outputs
    preprocessing_report: Dict[str, Any] = field(default_factory=dict)
    preprocessing_plan: Dict[str, Any] = field(default_factory=dict)
    preprocessing_code: Optional[str] = None
    preprocessing_report_path: Optional[Path] = None
    preprocessing_plan_path: Optional[Path] = None
    preprocessing_code_path: Optional[Path] = None
    processed_output_path: Optional[Path] = None
    # Report for processed_output.csv (generated by preprocessing workflow agent)
    processed_output_report_path: Optional[Path] = None
    
    # LLM Orchestrator outputs
    model_recommendations: Optional[str] = None
    selected_models: list[str] = field(default_factory=list)
    validation_code: Optional[str] = None
    validation_code_path: Optional[Path] = None
    trained_models: Dict[str, Path] = field(default_factory=dict)
    evaluation_results: Dict[str, Any] = field(default_factory=dict)
    # Full LLM Orchestrator memory snapshot (copied from orchestrator_memory.json)
    llm_orchestrator_memory: Dict[str, Any] = field(default_factory=dict)
    
    # Improvement Agent outputs
    optimization_report: Dict[str, Any] = field(default_factory=dict)
    optimized_code: Optional[str] = None
    optimization_report_path: Optional[Path] = None
    optimized_code_path: Optional[Path] = None
    
    # Complete file history across all agents
    file_history: Dict[str, str] = field(default_factory=dict)
    
    # Workflow history
    workflow_history: list[Dict[str, str]] = field(default_factory=list)


class MasterOrchestratorAgent:
    """
    Master AI Agent that orchestrates all agents and maintains ultimate memory.
    
    Manages workflow: Preprocessing -> LLM Orchestration -> Improvement
    """
    
    def __init__(
        self,
        model: str = DEFAULT_LLM_MODEL,
        endpoint: str = DEFAULT_LLM_ENDPOINT,
        output_dir: Optional[Path] = None
    ):
        """
        Initialize the master orchestrator agent.
        
        Args:
            model: LLM model name (default: "phi4")
            endpoint: LLM endpoint URL (default: "http://127.0.0.1:11434")
            output_dir: Directory to save outputs (default: project root)
        """
        self.model = model
        self.endpoint = endpoint
        self.output_dir = Path(output_dir) if output_dir else project_root
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Initialize ultimate memory
        self.memory = MasterMemory()
        
        # LangGraph workflow
        self.workflow = self._build_workflow_graph()
    
    # ========================================================================
    # STEP 1: PREPROCESSING AGENT
    # ========================================================================
    
    def run_preprocessing_agent(self, csv_path: Path, target_column: str, context: Optional[str] = None) -> Dict[str, Any]:
        """
        Step 1: Run Preprocessing Agent.
        
        This runs the preprocessing workflow agent which:
        - Generates dataset report
        - Generates preprocessing plan
        - Generates preprocessing code
        
        Args:
            csv_path: Path to the CSV dataset
            target_column: Name of the target column
            
        Returns:
            Generated preprocessing report dictionary
        """
        print("\n" + "="*70)
        print("STEP 1: Running Preprocessing Agent")
        print("="*70)
        
        # Store in memory - resolve to absolute path
        csv_path_resolved = csv_path.resolve()
        self.memory.dataset_path = csv_path_resolved
        self.memory.target_column = target_column
        self.memory.dataset_name = csv_path.stem
        if context:
            self.memory.context_of_dataset = context
        
        # Run preprocessing workflow agent using subprocess (like preprocessing_workflow_agent does)
        preprocessing_script = preprocessing_dir / "preprocessing_workflow_agent.py"
        if not preprocessing_script.exists():
            raise FileNotFoundError(f"Preprocessing agent script not found: {preprocessing_script}")
        
        # Verify dataset exists
        if not csv_path_resolved.exists():
            raise FileNotFoundError(f"Dataset not found: {csv_path_resolved}")
        
        print(f"Running preprocessing workflow agent...")
        print(f"  Dataset: {csv_path_resolved}")
        print(f"  Target: {target_column}")
        
        try:
            # Run preprocessing agent and wait for it to complete
            # Use absolute path so it works regardless of working directory
            print("Waiting for preprocessing agent to complete...")
            prep_output_dir = self.output_dir / "preprocessing"
            prep_output_dir.mkdir(parents=True, exist_ok=True)
            result = subprocess.run(
                [
                    sys.executable,
                    str(preprocessing_script),
                    "--csv", str(csv_path_resolved),
                    "--target", target_column,
                    "--model", self.model,
                    "--endpoint", self.endpoint,
                    "--output-dir", str(prep_output_dir),
                    "--save-memory"
                ],
                cwd=str(prep_output_dir),
                check=True,
            )
            
            print("\nPreprocessing agent completed successfully.")
            print("Copying preprocessing agent memory to master memory...")
            
            # Wait a moment for file to be written
            import time
            time.sleep(0.5)
            
            # Load preprocessing agent's memory to extract outputs
            prep_memory_file = prep_output_dir / "workflow_memory.json"
            if not prep_memory_file.exists():
                raise FileNotFoundError(
                    f"Preprocessing agent memory file not found: {prep_memory_file}. "
                    "The preprocessing agent may not have saved its memory."
                )
            
            with prep_memory_file.open("r", encoding="utf-8") as f:
                prep_memory = json.load(f)
            
            # Copy all preprocessing agent memory to master memory
            self._copy_preprocessing_memory(prep_memory)
            
            # Add to workflow history
            self._add_workflow_entry("Preprocessing Agent", "Completed successfully and memory copied")
            
            print(f"\nPreprocessing outputs copied to master memory:")
            print(f"  - Report: {self.memory.preprocessing_report_path}")
            print(f"  - Plan: {self.memory.preprocessing_plan_path}")
            print(f"  - Code: {self.memory.preprocessing_code_path}")
            
            return self.memory.preprocessing_report
            
        except subprocess.CalledProcessError as exc:
            error_msg = f"Preprocessing agent failed with exit code {exc.returncode}"
            if hasattr(exc, 'stderr') and exc.stderr:
                error_msg += f": {exc.stderr}"
            self._add_workflow_entry("Preprocessing Agent", f"Failed: {error_msg}")
            raise RuntimeError(error_msg) from exc
    
    def _copy_preprocessing_memory(self, prep_memory: Dict[str, Any]):
        """
        Copy all memory from preprocessing agent to master memory.
        
        Args:
            prep_memory: Dictionary loaded from preprocessing agent's workflow_memory.json
        """
        # Copy dataset info
        if prep_memory.get("dataset_path"):
            self.memory.dataset_path = Path(prep_memory["dataset_path"])
        if prep_memory.get("target_column"):
            self.memory.target_column = prep_memory["target_column"]
        if prep_memory.get("task_type"):
            self.memory.task_type = prep_memory["task_type"]
        if prep_memory.get("dataset_info", {}).get("dataset_name"):
            self.memory.dataset_name = prep_memory["dataset_info"]["dataset_name"]
        
        # Copy report and plan
        self.memory.preprocessing_report = prep_memory.get("report", {})
        self.memory.preprocessing_plan = prep_memory.get("preprocessing_plan", {})
        
        # Copy paths
        if prep_memory.get("report_path"):
            self.memory.preprocessing_report_path = Path(prep_memory["report_path"])
            self.memory.file_history["preprocessing_report"] = str(self.memory.preprocessing_report_path.resolve())
        
        if prep_memory.get("plan_path"):
            self.memory.preprocessing_plan_path = Path(prep_memory["plan_path"])
            self.memory.file_history["preprocessing_plan"] = str(self.memory.preprocessing_plan_path.resolve())
        
        if prep_memory.get("code_path"):
            self.memory.preprocessing_code_path = Path(prep_memory["code_path"])
            self.memory.file_history["preprocessing_code"] = str(self.memory.preprocessing_code_path.resolve())
            # Load code if file exists
            if self.memory.preprocessing_code_path.exists():
                try:
                    self.memory.preprocessing_code = self.memory.preprocessing_code_path.read_text(encoding="utf-8")
                except Exception:
                    pass  # If we can't read it, that's okay
        
        # Copy file history from preprocessing agent
        if prep_memory.get("file_history"):
            self.memory.file_history.update(prep_memory["file_history"])
        
        # Check for processed output — prefer per-job dir, fall back to agent dir
        prep_output_dir = self.output_dir / "preprocessing"
        processed_output = prep_output_dir / "processed_output.csv"
        if not processed_output.exists():
            processed_output = preprocessing_dir / "processed_output.csv"
        if processed_output.exists():
            self.memory.processed_output_path = processed_output.resolve()
            self.memory.file_history["processed_output"] = str(processed_output.resolve())
        
        # Copy processed output report path if it exists
        if prep_memory.get("processed_output_report_path"):
            self.memory.processed_output_report_path = Path(prep_memory["processed_output_report_path"])
            self.memory.file_history["processed_output_report"] = str(self.memory.processed_output_report_path.resolve())
    
    # ========================================================================
    # STEP 2: LLM ORCHESTRATOR (REASONING AGENT)
    # ========================================================================
    
    def run_llm_orchestrator(
        self,
        context: Optional[str] = None,
        test_size: float = 0.2,
        min_models: int = 1,
        max_models: int = 3
    ) -> Dict[str, Any]:
        """
        Step 2: Run LLM Orchestrator (Reasoning Agent).
        
        This runs the LLM Orchestrator workflow agent (in the 'LLM Orchestrator' folder) which:
        - Loads master_memory.json
        - Generates model recommendations
        - Generates and runs validation/testing code
        - Saves its own orchestrator_memory.json
        
        Args:
            context: Optional context for model recommendations
            test_size: Fraction of data for testing
            min_models: Minimum number of models to select
            max_models: Maximum number of models to select
            
        Returns:
            Dictionary with selected models and evaluation results
        """
        print("\n" + "="*70)
        print("STEP 2: Running LLM Orchestrator (LLM Orchestrator Workflow Agent)")
        print("="*70)
        
        # Ensure master memory is saved so the LLM Orchestrator can load it
        master_memory_path = self.output_dir / "master_memory.json"
        self.save_memory(master_memory_path)
        
        # Path to LLM Orchestrator workflow agent
        orchestrator_script = reasoning_dir / "llm_orchestrator_workflow_agent.py"
        if not orchestrator_script.exists():
            raise FileNotFoundError(f"LLM Orchestrator script not found: {orchestrator_script}")
        
        print(f"Using master memory: {master_memory_path}")
        
        try:
            # Run LLM Orchestrator workflow agent as a subprocess
            print("Running LLM Orchestrator workflow agent...")
            subprocess.run(
                [
                    sys.executable,
                    str(orchestrator_script),
                    "--master-memory",
                    str(master_memory_path),
                    "--save-memory",
                ],
                cwd=str(reasoning_dir),
                check=True,
            )
            
            # Load orchestrator memory
            orchestrator_memory_file = reasoning_dir / "orchestrator_memory.json"
            if not orchestrator_memory_file.exists():
                raise FileNotFoundError(
                    f"LLM Orchestrator memory file not found: {orchestrator_memory_file}"
                )
            
            with orchestrator_memory_file.open("r", encoding="utf-8") as f:
                orchestrator_memory = json.load(f)
            
            # Track orchestrator memory file in master file history
            self.memory.file_history["llm_orchestrator_memory"] = str(orchestrator_memory_file.resolve())
            # Store full orchestrator memory snapshot in master memory
            self.memory.llm_orchestrator_memory = orchestrator_memory
            
            # Extract recommended models and selected models for validation
            recommended_models = orchestrator_memory.get("recommended_models", [])
            selected_models_for_validation = orchestrator_memory.get("selected_models_for_validation", [])
            
            # Extract evaluation results from orchestrator memory if available
            validation_metrics = orchestrator_memory.get("validation_metrics", {})
            evaluation_results: Dict[str, Any] = {}
            validated_models: list[str] = []
            for model_name, info in validation_metrics.items():
                metrics = info.get("metrics", {})
                evaluation_results[model_name] = metrics
                validated_models.append(model_name)
            
            # Store in master memory
            # Store recommended models (all recommended)
            self.memory.selected_models = recommended_models if recommended_models else []
            # Store selected models for validation (user-selected for validation)
            # Note: selected_models field in MasterMemory will contain recommended models
            # The actual selected models for validation are stored in orchestrator_memory
            self.memory.evaluation_results = evaluation_results
            
            # Add to workflow history
            self._add_workflow_entry(
                "LLM Orchestrator",
                f"Completed successfully via workflow agent. Evaluated {len(validated_models)} model(s)."
            )
            
            print(f"\nLLM Orchestrator outputs (from orchestrator_memory.json):")
            print(f"  - Recommended models: {', '.join(recommended_models) if recommended_models else 'none'}")
            print(f"  - Selected for validation: {', '.join(selected_models_for_validation) if selected_models_for_validation else 'none'}")
            print(f"  - Evaluated models: {', '.join(validated_models) if validated_models else 'none'}")
            
            return {
                "recommended_models": recommended_models,
                "selected_models_for_validation": selected_models_for_validation,
                "validated_models": validated_models,
                "validation_code_path": None,
                "evaluation_results": evaluation_results,
            }
        except Exception as exc:
            error_msg = f"LLM Orchestrator failed: {exc}"
            self._add_workflow_entry("LLM Orchestrator", f"Failed: {error_msg}")
            raise
    
    # ========================================================================
    # STEP 3: IMPROVEMENT AGENT
    # ========================================================================
    
    def run_improvement_agent(self) -> Dict[str, Any]:
        """
        Step 3: Run Improvement Agent.
        
        This runs the improvement workflow agent which:
        - Loads master memory
        - Generates improvement steps
        - Generates improved validation code
        - Runs improved validation code and captures metrics
        - Updates master_memory.json with improvement results
        
        Args:
            None (uses master_memory.json)
            
        Returns:
            Dictionary with improvement agent results
        """
        print("\n" + "="*70)
        print("STEP 3: Running Improvement Agent")
        print("="*70)
        
        # Ensure master memory is saved so the Improvement Agent can load it
        master_memory_path = self.output_dir / "master_memory.json"
        self.save_memory(master_memory_path)
        
        # Path to Improvement Agent workflow agent
        improvement_script = improvement_dir / "improvement_workflow_agent.py"
        if not improvement_script.exists():
            raise FileNotFoundError(f"Improvement agent script not found: {improvement_script}")
        
        print(f"Using master memory: {master_memory_path}")
        
        try:
            # Run Improvement Agent workflow agent as a subprocess
            print("Running Improvement Agent workflow agent...")
            subprocess.run(
                [
                    sys.executable,
                    str(improvement_script),
                    "--master-memory",
                    str(master_memory_path),
                ],
                cwd=str(improvement_dir),
                check=True,
            )
            
            # Load improvement memory to extract outputs
            improvement_memory_file = improvement_dir / "improvement_memory.json"
            if not improvement_memory_file.exists():
                raise FileNotFoundError(
                    f"Improvement Agent memory file not found: {improvement_memory_file}"
                )
            
            with improvement_memory_file.open("r", encoding="utf-8") as f:
                improvement_memory = json.load(f)
            
            # Track improvement memory file in master file history
            self.memory.file_history["improvement_memory"] = str(improvement_memory_file.resolve())
            
            # Reload master memory to get updated improvement section
            if master_memory_path.exists():
                with master_memory_path.open("r", encoding="utf-8") as f:
                    updated_master_memory = json.load(f)
                
                # Extract improvement section from master memory
                improvement_section = updated_master_memory.get("improvement", {})
                if improvement_section:
                    # Update master memory with improvement results
                    self.memory.optimization_report = improvement_section.get("optimization_report", {})
                    if improvement_section.get("optimization_report_path"):
                        self.memory.optimization_report_path = Path(improvement_section["optimization_report_path"])
                    if improvement_section.get("optimized_code_path"):
                        self.memory.optimized_code_path = Path(improvement_section["optimized_code_path"])
            
            # Add to workflow history
            self._add_workflow_entry(
                "Improvement Agent",
                "Completed successfully via workflow agent."
            )
            
            print(f"\nImprovement Agent outputs (from improvement_memory.json):")
            print(f"  - Model: {improvement_memory.get('model_name', 'N/A')}")
            print(f"  - Improvement steps: {improvement_memory.get('improvement_steps_path', 'N/A')}")
            if improvement_memory.get("improved_validation_metrics"):
                print(f"  - Improved validation metrics: {improvement_memory.get('improved_validation_metrics')}")
            
            return {
                "improvement_memory_path": str(improvement_memory_file.resolve()),
                "model_name": improvement_memory.get("model_name"),
                "improved_validation_metrics": improvement_memory.get("improved_validation_metrics", {}),
            }
        except Exception as exc:
            error_msg = f"Improvement Agent failed: {exc}"
            self._add_workflow_entry("Improvement Agent", f"Failed: {error_msg}")
            raise
    
    # ========================================================================
    # COMPLETE WORKFLOW
    # ========================================================================
    
    def run_full_workflow(
        self,
        csv_path: Path,
        target_column: str,
        dataset_context: Optional[str] = None,
        llm_context: Optional[str] = None,
        test_size: float = 0.2,
        min_models: int = 1,
        max_models: int = 3,
        run_improvement: bool = True
    ) -> Dict[str, Any]:
        """
        Run the workflow: Currently only Preprocessing Agent.
        
        Other agents (LLM Orchestrator, Improvement) will be added later.
        
        Args:
            csv_path: Path to the CSV dataset
            target_column: Name of the target column
            dataset_context: Optional context/description of the dataset
            llm_context: Optional context for model recommendations (not used yet)
            test_size: Fraction of data for testing (not used yet)
            min_models: Minimum number of models to select (not used yet)
            max_models: Maximum number of models to select (not used yet)
            run_improvement: Whether to run improvement agent (not used yet)
            
        Returns:
            Dictionary with workflow results
        """
        print("\n" + "="*70)
        print("MASTER ORCHESTRATOR - WORKFLOW")
        print("="*70)
        print("Currently running: Preprocessing Agent + LLM Orchestrator + Improvement Agent")
        print("="*70)
        
        # Store dataset context in memory
        if dataset_context:
            self.memory.context_of_dataset = dataset_context
        
        initial_state = {
            "dataset_path": str(csv_path),
            "target_column": target_column,
            "dataset_context": dataset_context,
            "llm_context": llm_context,
            "test_size": test_size,
            "min_models": min_models,
            "max_models": max_models,
            "run_improvement": run_improvement,
            "status": "pending"
        }
        
        result_state = self.workflow.invoke(initial_state)
        
        if result_state.get("status") == "success":
            print("\n" + "="*70)
            print("WORKFLOW FINISHED SUCCESSFULLY")
            print("="*70)
            self._print_summary()
            
            return {
                "status": "success",
                "memory": self.get_memory(),
                "preprocessing": {
                    "report_path": str(self.memory.preprocessing_report_path) if self.memory.preprocessing_report_path else None,
                    "plan_path": str(self.memory.preprocessing_plan_path) if self.memory.preprocessing_plan_path else None,
                    "code_path": str(self.memory.preprocessing_code_path) if self.memory.preprocessing_code_path else None,
                }
            }
        
        error_message = result_state.get("error", "Unknown error")
        print(f"\nERROR: Workflow failed: {error_message}")
        return {
            "status": "error",
            "error": error_message,
            "memory": self.get_memory()
        }
    
    # ========================================================================
    # MEMORY MANAGEMENT
    # ========================================================================
    
    def get_memory(self) -> Dict[str, Any]:
        """
        Get the complete master memory.
        
        Returns:
            Dictionary containing all stored memory across all agents
        """
        return {
            # Core dataset info
            "dataset_path": str(self.memory.dataset_path) if self.memory.dataset_path else None,
            "target_column": self.memory.target_column,
            "dataset_name": self.memory.dataset_name,
            "context_of_dataset": self.memory.context_of_dataset,
            "task_type": self.memory.task_type,
            
            # Preprocessing Agent outputs
            "preprocessing": {
                "report": self.memory.preprocessing_report,
                "plan": self.memory.preprocessing_plan,
                "code_length": len(self.memory.preprocessing_code) if self.memory.preprocessing_code else 0,
                "report_path": str(self.memory.preprocessing_report_path) if self.memory.preprocessing_report_path else None,
                "plan_path": str(self.memory.preprocessing_plan_path) if self.memory.preprocessing_plan_path else None,
                "code_path": str(self.memory.preprocessing_code_path) if self.memory.preprocessing_code_path else None,
                "processed_output_path": str(self.memory.processed_output_path) if self.memory.processed_output_path else None,
                "processed_output_report_path": str(self.memory.processed_output_report_path) if self.memory.processed_output_report_path else None,
            },
            
            # LLM Orchestrator outputs
            "llm_orchestrator": {
                # Full orchestrator memory (direct copy of orchestrator_memory.json contents, including reasons and code paths)
                # Contains: recommended_models, selected_models_for_validation, model_recommendations_structured, etc.
                "orchestrator_memory": self.memory.llm_orchestrator_memory,
            },
            
            # Improvement Agent outputs
            "improvement": {
                "optimization_report": self.memory.optimization_report,
                "optimized_code_length": len(self.memory.optimized_code) if self.memory.optimized_code else 0,
                "optimization_report_path": str(self.memory.optimization_report_path) if self.memory.optimization_report_path else None,
                "optimized_code_path": str(self.memory.optimized_code_path) if self.memory.optimized_code_path else None,
            },
            
            # Complete file history
            "file_history": self.memory.file_history,
            
            # Workflow history
            "workflow_history": self.memory.workflow_history,
        }
    
    def save_memory(self, path: Optional[Path] = None):
        """
        Save master memory to a JSON file.
        
        Args:
            path: Path to save memory (default: output_dir/master_memory.json)
        """
        if path is None:
            path = self.output_dir / "master_memory.json"
        
        memory_dict = self.get_memory()
        
        # Don't save full code in memory file (too large)
        if memory_dict["preprocessing"].get("code"):
            memory_dict["preprocessing"]["code_length"] = len(self.memory.preprocessing_code) if self.memory.preprocessing_code else 0
        if memory_dict["llm_orchestrator"].get("validation_code"):
            memory_dict["llm_orchestrator"]["validation_code_length"] = len(self.memory.validation_code) if self.memory.validation_code else 0
        if memory_dict["improvement"].get("optimized_code"):
            memory_dict["improvement"]["optimized_code_length"] = len(self.memory.optimized_code) if self.memory.optimized_code else 0
        
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            json.dump(memory_dict, f, indent=2)
        
        print(f"\nMaster memory saved to: {path}")
    
    def load_memory(self, path: Path):
        """
        Load master memory from a JSON file.
        
        Args:
            path: Path to load memory from
        """
        if not path.exists():
            raise FileNotFoundError(f"Memory file not found: {path}")
        
        with path.open("r", encoding="utf-8") as f:
            memory_dict = json.load(f)
        
        # Restore core dataset info
        if memory_dict.get("dataset_path"):
            self.memory.dataset_path = Path(memory_dict["dataset_path"])
        self.memory.target_column = memory_dict.get("target_column")
        self.memory.dataset_name = memory_dict.get("dataset_name")
        self.memory.context_of_dataset = memory_dict.get("context_of_dataset")
        self.memory.task_type = memory_dict.get("task_type")
        
        # Restore preprocessing memory
        prep = memory_dict.get("preprocessing", {})
        self.memory.preprocessing_report = prep.get("report", {})
        self.memory.preprocessing_plan = prep.get("plan", {})
        if prep.get("report_path"):
            self.memory.preprocessing_report_path = Path(prep["report_path"])
        if prep.get("plan_path"):
            self.memory.preprocessing_plan_path = Path(prep["plan_path"])
        if prep.get("code_path"):
            self.memory.preprocessing_code_path = Path(prep["code_path"])
            if self.memory.preprocessing_code_path.exists():
                self.memory.preprocessing_code = self.memory.preprocessing_code_path.read_text(encoding="utf-8")
        
        # Restore LLM orchestrator memory
        llm = memory_dict.get("llm_orchestrator", {})
        self.memory.selected_models = llm.get("selected_models", [])
        self.memory.evaluation_results = llm.get("evaluation_results", {})
        # Restore full LLM orchestrator memory snapshot if present
        if llm.get("orchestrator_memory"):
            try:
                self.memory.llm_orchestrator_memory = dict(llm["orchestrator_memory"])
            except Exception:
                self.memory.llm_orchestrator_memory = llm.get("orchestrator_memory", {})
        if llm.get("validation_code_path"):
            self.memory.validation_code_path = Path(llm["validation_code_path"])
            if self.memory.validation_code_path.exists():
                self.memory.validation_code = self.memory.validation_code_path.read_text(encoding="utf-8")
        
        # Restore improvement memory
        imp = memory_dict.get("improvement", {})
        self.memory.optimization_report = imp.get("optimization_report", {})
        if imp.get("optimization_report_path"):
            self.memory.optimization_report_path = Path(imp["optimization_report_path"])
        if imp.get("optimized_code_path"):
            self.memory.optimized_code_path = Path(imp["optimized_code_path"])
            if self.memory.optimized_code_path.exists():
                self.memory.optimized_code = self.memory.optimized_code_path.read_text(encoding="utf-8")
        
        # Restore file history
        if memory_dict.get("file_history"):
            self.memory.file_history = memory_dict["file_history"]
        
        # Restore workflow history
        if memory_dict.get("workflow_history"):
            self.memory.workflow_history = memory_dict["workflow_history"]
        
        print(f"Master memory loaded from: {path}")
    
    def _add_workflow_entry(self, agent: str, message: str):
        """Add an entry to workflow history."""
        self.memory.workflow_history.append({
            "agent": agent,
            "message": message
        })
    
    def _print_summary(self):
        """Print a summary of the complete workflow."""
        print(f"\nDataset: {self.memory.dataset_path}")
        print(f"Target: {self.memory.target_column}")
        print(f"\nPreprocessing Agent:")
        print(f"  - Report: {self.memory.preprocessing_report_path}")
        print(f"  - Plan: {self.memory.preprocessing_plan_path}")
        print(f"  - Code: {self.memory.preprocessing_code_path}")
        print(f"\nLLM Orchestrator:")
        print(f"  - Selected models: {', '.join(self.memory.selected_models)}")
        print(f"  - Validation code: {self.memory.validation_code_path}")
        print(f"\nImprovement Agent:")
        if self.memory.optimization_report_path:
            print(f"  - Optimization report: {self.memory.optimization_report_path}")
        if self.memory.optimized_code_path:
            print(f"  - Optimized code: {self.memory.optimized_code_path}")
    
    # ========================================================================
    # LANGRAPH WORKFLOW GRAPH
    # ========================================================================
    
    def _build_workflow_graph(self):
        """Build a LangGraph state graph that coordinates the workflow."""
        class WorkflowState(TypedDict, total=False):
            dataset_path: str
            target_column: str
            dataset_context: Optional[str]
            llm_context: Optional[str]
            test_size: float
            min_models: int
            max_models: int
            run_improvement: bool
            status: Literal["pending", "ok", "error", "success"]
            error: str
            memory_snapshot: Dict[str, Any]
        
        state_graph = StateGraph(WorkflowState)
        state_graph.add_node("preprocessing", self._graph_preprocessing)
        state_graph.add_node("llm_orchestration", self._graph_llm_orchestration)
        state_graph.add_node("improvement", self._graph_improvement)
        state_graph.add_node("persist_memory", self._graph_finalize_memory)
        
        state_graph.set_entry_point("preprocessing")
        state_graph.add_conditional_edges(
            "preprocessing",
            self._status_router,
            {"error": END, "ok": "llm_orchestration"}
        )
        state_graph.add_conditional_edges(
            "llm_orchestration",
            self._status_router,
            {"error": END, "ok": "improvement"}
        )
        state_graph.add_conditional_edges(
            "improvement",
            self._status_router,
            {"error": END, "ok": "persist_memory"}
        )
        state_graph.add_edge("persist_memory", END)
        
        return state_graph.compile()
    
    @staticmethod
    def _status_router(state: Dict[str, Any]) -> str:
        """Determine next edge based on state."""
        return "error" if state.get("status") == "error" else "ok"
    
    def _graph_preprocessing(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """LangGraph node: run preprocessing agent."""
        csv_path = Path(state["dataset_path"])
        target_column = state["target_column"]
        dataset_context = state.get("dataset_context")
        try:
            self.run_preprocessing_agent(csv_path, target_column, context=dataset_context)
            return {"status": "ok", "error": ""}
        except Exception as exc:
            return {"status": "error", "error": str(exc)}
    
    def _graph_llm_orchestration(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """LangGraph node: run LLM orchestrator."""
        try:
            self.run_llm_orchestrator(
                context=state.get("llm_context"),
                test_size=state.get("test_size", 0.2),
                min_models=state.get("min_models", 1),
                max_models=state.get("max_models", 3),
            )
            return {"status": "ok", "error": ""}
        except Exception as exc:
            return {"status": "error", "error": str(exc)}
    
    def _graph_improvement(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """LangGraph node: run improvement agent. Skip when user selected full dataset (LLM Orchestrator already ran it)."""
        if not state.get("run_improvement", True):
            return {"status": "ok", "error": ""}
        # When user selected train on full dataset, LLM Orchestrator workflow already ran full training; skip improvement agent
        if self.memory.llm_orchestrator_memory.get("selected_model_for_full_training"):
            print("\nFull dataset training was selected; Improvement Agent skipped (full training already run by LLM Orchestrator).")
            self._add_workflow_entry("Improvement Agent", "Skipped (full dataset training was selected; run by LLM Orchestrator).")
            return {"status": "ok", "error": ""}
        try:
            self.run_improvement_agent()
            return {"status": "ok", "error": ""}
        except Exception as exc:
            return {"status": "error", "error": str(exc)}
    
    def _graph_finalize_memory(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Final LangGraph node: capture memory snapshot."""
        snapshot = self.get_memory()
        return {
            "memory_snapshot": snapshot,
            "status": "success"
        }


def main():
    """Main entry point for command-line usage."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Master Orchestrator Agent - Coordinates all agents in the FYP workflow"
    )
    parser.add_argument(
        "--csv",
        type=Path,
        required=True,
        help="Path to the CSV dataset"
    )
    parser.add_argument(
        "--target",
        type=str,
        required=True,
        help="Name of the target column"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory to save outputs (default: project root)"
    )
    parser.add_argument(
        "--model",
        type=str,
        default=DEFAULT_LLM_MODEL,
        help=f"LLM model name (default: {DEFAULT_LLM_MODEL})"
    )
    parser.add_argument(
        "--endpoint",
        type=str,
        default=DEFAULT_LLM_ENDPOINT,
        help=f"LLM endpoint URL (default: {DEFAULT_LLM_ENDPOINT})"
    )
    parser.add_argument(
        "--dataset-context",
        type=str,
        default=None,
        help="Context/description of the dataset"
    )
    parser.add_argument(
        "--context",
        type=str,
        default=None,
        help="Context for model recommendations"
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.2,
        help="Fraction of data for testing (default: 0.2)"
    )
    parser.add_argument(
        "--min-models",
        type=int,
        default=1,
        help="Minimum number of models to select (default: 1)"
    )
    parser.add_argument(
        "--max-models",
        type=int,
        default=3,
        help="Maximum number of models to select (default: 3)"
    )
    parser.add_argument(
        "--skip-improvement",
        action="store_true",
        help="Skip improvement agent"
    )
    parser.add_argument(
        "--save-memory",
        action="store_true",
        help="Save master memory to JSON file"
    )
    
    args = parser.parse_args()
    
    # Initialize master orchestrator
    orchestrator = MasterOrchestratorAgent(
        model=args.model,
        endpoint=args.endpoint,
        output_dir=args.output_dir
    )
    
    # Run complete workflow
    result = orchestrator.run_full_workflow(
        csv_path=args.csv,
        target_column=args.target,
        dataset_context=args.dataset_context,
        llm_context=args.context,
        test_size=args.test_size,
        min_models=args.min_models,
        max_models=args.max_models,
        run_improvement=not args.skip_improvement
    )
    
    # Save memory if requested
    if args.save_memory:
        orchestrator.save_memory()
    
    # Exit with appropriate code
    sys.exit(0 if result["status"] == "success" else 1)


if __name__ == "__main__":
    main()

